name = "ap"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["AP", "main"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
linter.style.longLine = true
backward.isDefEq.respectTransparency = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "tryAtEachStep"
git = "https://github.com/dwrensha/tryAtEachStep"
rev = "main"

[[lean_lib]]
name = "AP"

[[lean_exe]]
name = "main"
root = "AP"
needs = ["AP"]