import Projects.Util.Basic
import Projects.Util.Serializable.Serializer

-- structure Deserializer where
--   bytes : ByteArray
--   bitIndex : ℕ
-- deriving DecidableEq
-- 
-- abbrev DSer := StateM Deserializer
-- 
-- namespace Deserializer
-- 
-- open Serializer
-- 
-- def init (bytes : ByteArray) : Deserializer where
--   bytes := bytes
--   bitIndex := 0
-- 
-- def byteIndex : DSer ℕ :=
--   gets (·.bitIndex >>> 3)
-- 
-- def inByteBitIndex : DSer UInt8 :=
--   gets (·.bitIndex &&& 7 |>.toUInt8)
-- 
-- def curByte : DSer UInt8 := do
--   pure # (←get).bytes.getD 0 (←byteIndex)
-- 
-- def next' : DSer Unit := modify # λ d =>
--   { bytes := d.bytes
--     bitIndex := d.bitIndex + 1
--   }
-- 
-- def eof : DSer Bool :=
--   gets # λ d => d.bytes.size ≤ d.bitIndex
-- 
-- def toEof : DSer Unit := modify # λ d =>
--   { bytes := d.bytes
--     bitIndex := d.bytes.size
--   }
-- 
-- def next : DSer Unit := do
--   if ←eof then pure () else next'
-- 
-- def readBit' : DSer Bit := do
--   pure # ((←curByte) >>> (←inByteBitIndex)) &&& 1 != 0
-- 
-- def readBit : DSer Bit := do
--   let b ← readBit'
--   next; pure b
-- 
-- def drop (n : ℕ) : DSer Unit := modify # λ d =>
--   { bytes := d.bytes
--     bitIndex := min d.bytes.size # d.bitIndex + n
--   }
-- 
-- def queryAllBits' (d : Deserializer) (n : ℕ) : List Bit :=
--   match n with
--   | 0 => []
--   | n + 1 =>
--     let (b, d') := d.readBit
--     b :: d'.queryAllBits' n
-- 
-- def queryAllBits : DSer # List Bit :=
--   gets # λ d => queryAllBits' d # d.bytes.size * 8 - d.bitIndex
-- 
-- def skipBits (n : ℕ) : DSer Unit := modify # λ d =>
--   { bytes := d.bytes
--     bitIndex := d.bitIndex + n
--   }
-- 
-- -----
-- 
-- variable {α β γ : Type}
-- variable {d : Deserializer}
-- 
-- @[simp]
-- theorem skipBits_zero : skipBits 0 = pure () := rfl
-- 
-- @[simp]
-- theorem const_fmap_queryAllBits {x : α} : (λ _ => x) <$> queryAllBits = pure x := rfl
-- 
-- @[simp]
-- theorem snd_queryAllBits : (queryAllBits.run d).2 = d := by
--   simp [queryAllBits]
-- 
-- @[simp] theorem bytes_init {bs} : (init bs).bytes = bs := rfl
-- @[simp] theorem bitIndex_init {bs} : (init bs).bitIndex = 0 := rfl
-- 
-- -- theorem fst_queryAllBits_init_cons {b bs} : (queryAllBits.run (init ⟨⟨b :: bs⟩⟩)).1 =
-- -- b.toBits ++ (queryAllBits.run (init ⟨⟨bs⟩⟩)).1 := by
-- --   simp [queryAllBits]
-- --   simp_rw [ByteArray.size]
-- --   simp [Nat.add_mul]
-- --   simp [init]
-- --   generalize hn : 8 = n; symm at hn
-- --   rw [hn]; nth_rw 2 [←hn]
-- --   sorry
-- -- 
-- -- -- #check 0 #exit
-- -- 
-- -- @[simp]
-- -- theorem fst_queryAllBits_init {bs} :
-- -- queryAllBits.run (init bs) = (bs.toBits, init bs) := by
-- --   rcases bs with ⟨⟨bs⟩⟩
-- --   rw [Prod.ext_iff]
-- --   symm; split_ands; simp
-- --   simp [ByteArray.toBits]
-- --   induction bs; rfl
-- --   nm b bs ih
-- --   rw [fst_queryAllBits_init_cons]
-- --   simpa [List.flatMap_cons]
-- -- 
-- -- @[simp]
-- -- theorem queryAllBits_init_bytes_bytes_ser_ofBits {bs} :
-- -- queryAllBits.run (init # ofBits bs |>.bytes) =
-- -- (bs ++ .replicate (bs.length % 8) 0, init (ofBits bs).bytes) := by
-- --   simp
-- --   congr
-- --   sorry